GUA - 431 dead letter queues
alphagov/di-account-management-backend pull request #23
Opened 2022-10-20 10:42 UTC by divyaparameswaran

This PR adds the Dead Letter queue configuration to the format user service and query user service lambda. 
- If an error of any kind occurs during the process the record is sent to the Dead Letter Queue.
- I have also included some fix for listing errors in `format-user-services.test.ts` regarding an unused var.
- Also renamed format-user-record.test to format-user-service to match the handler ts.

2022-10-20 14:04 UTC, huwd requested changes
The linter has one or two things that it wants corrected.
Otherwise looks good

2022-10-20 14:04 UTC, huwd commented on lambda/query-user-services/query-user-services.ts
> +  messageBody: object,
Interesting, what caused the shift from a specific interface to `object`? I'm assuming `object` is just a generic for any `{}`.

Ideally I'd like to keep these specific?

2022-10-20 14:04 UTC, huwd commented on lambda/query-user-services/tests/query-user-services.test.ts
> +    consoleErrorMock = jest.spyOn(global.console, "error").mockImplementation();
Ooh cool, I was wondering how to do that. Nice one.

2022-10-20 14:04 UTC, huwd commented on lambda/format-user-services/tests/format-user-services.test.ts
> +import { UserServices, Service, TxmaEvent } from "../models";
looks like there's a linting error here.
Let's have a chat about getting prettier set up in vscode it should autoremove things like this under some conditions!

2022-10-20 14:04 UTC, huwd commented on lambda/format-user-services/tests/format-user-services.test.ts
> +import { UserServices, Service, TxmaEvent } from "../models";
ah wait, I see there's a clash with types declared below 🤔 
Ok perhaps best that this line becomes:

```suggestion
import type { UserServices, Service, TxmaEvent } from "../models";
```

Then remove TxmaEvent if it's not being used
and lines 144 and 161 should be `txmaEvent` to follow converntion as constants I think!

2022-10-20 14:04 UTC, huwd commented on lambda/format-user-services/tests/format-user-services.test.ts
> +  const userId = "userID1234";
might need to go if it's not being used

2022-10-20 14:04 UTC, huwd commented on lambda/format-user-services/tests/format-user-services.test.ts
> +  const serviceClientID = "clientID1234";
might need to go if it's not being used

2022-10-21 10:06 UTC, alex9smith approved these changes
👍🏻

2022-10-21 14:20 UTC, huwd approved these changes

2022-10-21 14:32 UTC, merged